name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6']
        active_record: ['5.2', '6.0']
        dry_types: ['1.0', '1.2']
        include:
          - ruby: '2.7'
            active_record: '6.1'
            dry_types: '1.6'
          - ruby: '2.7'
            active_record: '7.0'
            dry_types: '1.6'
          - ruby: '2.7'
            active_record: '7.1'
            dry_types: '1.6'
          - ruby: '3.0'
            active_record: '6.1'
            dry_types: '1.6'
          - ruby: '3.0'
            active_record: '7.0'
            dry_types: '1.6'
          - ruby: '3.0'
            active_record: '7.1'
            dry_types: '1.6'
          - ruby: '3.1'
            active_record: '7.0'
            dry_types: '1.6'
          - ruby: '3.1'
            active_record: '7.1'
            dry_types: '1.6'
          - ruby: '3.1'
            active_record: '7.2'
            dry_types: '1.6'
          - ruby: '3.2'
            active_record: '7.0'
            dry_types: '1.6'
          - ruby: '3.2'
            active_record: '7.1'
            dry_types: '1.6'
          - ruby: '3.2'
            active_record: '7.2'
            dry_types: '1.6'
          - ruby: '3.2'
            active_record: '8.0'
            dry_types: '1.6'
          - ruby: '3.3'
            active_record: '7.1'
            dry_types: '1.6'
          - ruby: '3.3'
            active_record: '7.2'
            dry_types: '1.6'
          - ruby: '3.3'
            active_record: '8.0'
            dry_types: '1.6'
          - ruby: '3.4'
            active_record: '7.2'
            dry_types: '1.6'
          - ruby: '3.4'
            active_record: '8.0'
            dry_types: '1.6'

    env:
      ACTIVERECORD: ${{ matrix.active_record }}
      DRY_TYPES: ${{ matrix.dry_types }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
